# Generated by Django 5.1 on 2025-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_data_storage', '0003_delete_server_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField(null=True)),
                ('cpu_count', models.FloatField(null=True)),
                ('cpu_freq_current', models.FloatField(null=True)),
                ('getloadavg_1min', models.FloatField(null=True)),
                ('getloadavg_5min', models.FloatField(null=True)),
                ('getloadavg_15min', models.FloatField(null=True)),
                ('virtual_memory_total', models.FloatField(null=True)),
                ('virtual_memory_used', models.FloatField(null=True)),
                ('virtual_memory_available', models.FloatField(null=True)),
                ('virtual_memory_free', models.FloatField(null=True)),
                ('virtual_memory_percent', models.FloatField(null=True)),
                ('swap_memory_total', models.FloatField(null=True)),
                ('swap_memory_used', models.FloatField(null=True)),
                ('swap_memory_free', models.FloatField(null=True)),
                ('swap_memory_percent', models.FloatField(null=True)),
                ('disk_usage_total', models.FloatField(null=True)),
                ('disk_usage_used', models.FloatField(null=True)),
                ('disk_usage_free', models.FloatField(null=True)),
                ('disk_usage_percent', models.FloatField(null=True)),
                ('net_io_counters_lo_bytes_sent', models.FloatField(null=True)),
                ('net_io_counters_lo_bytes_recv', models.FloatField(null=True)),
                ('net_io_counters_eth0_bytes_sent', models.FloatField(null=True)),
                ('net_io_counters_eth0_bytes_recv', models.FloatField(null=True)),
            ],
        ),
    ]
